title: Daily Mail for Tech news
description:  A place for my daily brain food.
show_downloads: false
theme: jekyll-theme-cayman
permalink: /blog/:title/
plugins:
  - jekyll-paginate

paginate: 10 # Number of posts per page
paginate_path: "/page:num/"